<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_visit-date</name>
   <tag></tag>
   <elementGuidId>2fa3a9e2-5e90-4ebd-9813-4e0889861b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#txt_visit_date</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_visit_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
